# Generated by Django 3.2.8 on 2021-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('cover_image', models.CharField(max_length=200)),
            ],
        ),
    ]
