# Generated by Django 3.2.8 on 2021-10-26 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='born',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composer',
            name='died',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
