# Generated by Django 3.2.8 on 2021-10-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0001_initial'),
        ('composers', '0002_auto_20211026_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='died',
        ),
        migrations.AddField(
            model_name='composer',
            name='piece',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composers', to='piece.piece'),
        ),
    ]
